<?php

interface IGeolocationConstants
{

    const OK = "OK";

    const RESPONSE_IS_NULL = "RESPONSE_IS_NULL";

    const NOT_FOUND = "NOT_FOUND";

    const SERVICE_STATUS_FAILED = "SERVICE_STATUS_FAILED";

    const SERVICE_STATUS_EXC = "SERVICE_STATUS_EXC";

    const SERVICE_NOT_OK = "SERVICE_NOT_OK";

    const SERVICE_INVALID_RESPONSE = "SERVICE_INVALID_RESPONSE";

    const SERVICE_NOT_AVAILABLE = "SERVICE_NOT_AVAILABLE";
}